[project]
name = "tkchart"
version = "1.3.2"
authors = [
  { name="Thisal-D"},
]
description = "tkchart Library is a Python library that simplifies the process of creating line charts in tkinter and customtkinter GUI applications."
readme = "README.md"
requires-python = ">=3.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/Thisal-D/tkchart"
Issues = "https://github.com/Thisal-D/tkchart/issues"